config/routes.rb
Rails.application.routes.draw do
  resources :stores

  root 'welcome#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  
 validates :Store_Name ,:Manager, :City, :Country ,:Zipcode, :State ,:presence =>"true"
 validates:Store_Name ,:uniqueness =>"true"

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  
  def index
    @stores=Store.all
  end 
  
  def show
  @store=Store.find(params[:id])
  end
  
  def new
  @store=Store.new
  end
  
  def create
  @store=Store.new(store_params)
  
  
  if @store.save
    redirect_to stores_path, :notice => "Your store was saved"
    
  else
    render "new"
     
  end
  
  end
  
  def edit
  	@store = Store.find(params[:id])
  end
  
  def update
  @store=Store.find(params[:id])
  
	if @store.update(store_params)
			redirect_to stores_path, :notice =>"Your store updated"
		else
			render 'edit'
		end
  
  end
  
  def destroy
    @store=Store.find(params[:id])
    @store.destroy
    redirect_to stores_path, :notice =>"store deleted"
  end
  
  
  	private 
		def store_params
			params.require(:store).permit(:Store_Name,:Manager,:City,:Zipcode,:State,:Country)
		end	
		
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
<p>
  <%= value %>
  
</p>

<% end %>
<%= yield %>


</body>
</html>

app/views/stores/edit.html.erb
<h1  class="storeh1">Edit Store</h1>




<div class="displaydiv2">
  
  <%= form_for @store do |f| %>

<% if @store.errors.any? %>
<h2>Errors</h2>
<ul >
  <% @store.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  
  <% end %>
</ul>

<% end %>
  


<p>
  
  <%= f.label :Store_Name %>
  <%= f.text_field :Store_Name %>
  
</p>

<p>
  
  <%= f.label :Manager %>
  <%= f.text_field :Manager %>
  
</p>

<p>
  
  <%= f.label :City %>
  <%= f.text_field :City %>
  
</p>

<p>
  
  <%= f.label :Zipcode %>
  <%= f.text_field :Zipcode %>
  
</p>

<p>
  
  <%= f.label :State %>
  <%= f.text_field :State %>
  
</p>

<p>
  
  <%= f.label :Country %>
  <%= f.text_field :Country %>
  
</p>


<p>
  </br>

  <%= f.submit "Update Store" ,:class=>"button"%> &nbsp &nbsp &nbsp &nbsp
   <%= link_to '<button type="button" class="button">Back</button>'.html_safe, stores_path %>
  
</p>

</div>


<% end %>

app/views/stores/index.html.erb
<div class="storediv">
<h1  class="storeh1">Stores Directory</h1>

<table id="stores" class="storetable">
  <thead>
  <tr>

  
  <th>Store_Name</th>
    <th>Manager</th>
  	<th>City</th>
  	 <th>Zipcode</th>
    <th>State</th>
    <th>Country</th>
 

  </tr>
  
</thead>
    



<tbody>
  <% @stores.each do |store| %>
  
<tr>
    <td><%= link_to store.Store_Name,store %></td>
    <td> <%= store.Manager %> </td>
    <td> <%= store.City %> </td>
    <td> <%= store.Zipcode %> </td>
    <td> <%= store.State %> </td>
    <td> <%= store.Country %> </td>
</tr>

<% end %>
</tbody>

</table>
</div>
<p><%= link_to '<button type="button" class="button">Add New Store</button>'.html_safe,new_store_path %></p>

app/views/stores/new.html.erb
<h1 class="storeh1">Add a new Store</h1>
<%= form_for @store do |f| %>

<% if @store.errors.any? %>
<h2>Errors</h2>
<ul >
  <% @store.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  
  <% end %>
</ul>

<% end %>




<div class="displaydiv2">
<p>
  
  <%= f.label :Store_Name,class:'required' %>
  <%= f.text_field :Store_Name %>
  
</p>

<p>
  
  <%= f.label :Manager ,class:'required'%>
  <%= f.text_field :Manager %>
  
</p>

<p>
  
  <%= f.label :City,class:'required' %>
  <%= f.text_field :City %>
  
</p>

<p>
  
  <%= f.label :Zipcode,class:'required' %>
  <%= f.text_field :Zipcode %>
  
</p>

<p>
  
  <%= f.label :State,class:'required' %>
  <%= f.text_field :State %>
  
</p>

<p>
  
  <%= f.label :Country ,class:'required' %>
  <%= f.text_field :Country %>
  
</p>


<p>
  
</br> </br>
  <%= f.submit "Submit",:class=>"button" %> &nbsp &nbsp &nbsp &nbsp

  <%= link_to '<button type="button" class="button" >Back</button>'.html_safe, stores_path %>
  
</p>

</div>

<% end %>

app/views/stores/show.html.erb
<h1 class="storeh1">Store Details</h1>
<div class="displaydiv2">

 

  <p>
  <label class="thicker">Store_Name :</label>  <%= @store.Store_Name %>   
  </p>
  
  <p>
      <label class="thicker">Manager    :</label><%= @store.Manager %>
  </p>
  
  <p>
      <label class="thicker">City       :</label><%= @store.City %>
  </p>
  
  <p>
      <label class="thicker">Zipcode    :</label><%= @store.Zipcode %>
  </p>
  
  <p>
       <label class="thicker">State      :</label><%= @store.State %>
  </p>
  
 <p>
      <label class="thicker">Country    :</label><%= @store.Country %>
 </p>
 
 


</div>
<div class="displaydiv3">
    <p>
        <%= link_to '<button type="button" class="button">Edit</button>'.html_safe, edit_store_path(@store) %> &nbsp &nbsp 
       
        <%= link_to '<button type="button" class="button">Delete</button>'.html_safe, store_path(@store),
                                         method: :delete,
                                         data: { confirm: 'Are you sure?' } %>&nbsp &nbsp
          
          
           <%= link_to '<button type="button" class="button">Back</button>'.html_safe, stores_path %>
          
          </p>
        
      
  
</div>

app/views/welcome/index.html.erb
<div class="welcomediv">
<h1 class="storeh1">Welcome</h1>
<p>This is a stores website where you can view details about the store.</p>

<%= link_to '<button type="button" class="button" >View Stores</button>'.html_safe, stores_path %>
</div>